IMAGE_NAME = "geerlingguy/ubuntu1804"
N = 1
CIDR_PREFIX = "10.0.0."

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  (1..N).each do |i|
    config.vm.define "zk0#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network "private_network", ip: CIDR_PREFIX+"#{10+i}"
      node.vm.hostname = "zk0#{i}"
    end
  end
end
